---
#File generate by this command:  kubectl create clusterrolebinding expose-crb --clusterrole=expose-cr --serviceaccount expose:expose-sa --dry-run=client -o yaml > manifests/crb.yaml 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: expose-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: expose-cr
subjects:
- kind: ServiceAccount
  name: expose-sa
  namespace: expose
